kind: Namespace
apiVersion: v1
metadata:
  name: default
  labels:
    {{- include "go-echo.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled

